# Generated by Django 2.0.6 on 2018-06-16 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True, help_text='Date when job was created')),
                ('date_ended', models.DateField(default=None, help_text='Date when the job ended', null=True)),
                ('is_failed', models.BooleanField(default=False, help_text='Whether the job failed or not')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.TextField(help_text='The xpath which contains a positive label')),
                ('job', models.ForeignKey(help_text='The classification job this result corresponds to', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='classification.ClassificationJob')),
            ],
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=255)),
                ('date_trained', models.DateTimeField(auto_now_add=True, help_text='Date trained')),
                ('serialized', models.BinaryField(help_text='Pickle')),
            ],
        ),
        migrations.CreateModel(
            name='PageDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(help_text='Url', validators=[django.core.validators.URLValidator()])),
                ('content', models.TextField(help_text='Html content')),
                ('date_downloaded', models.DateTimeField(auto_now_add=True, help_text='Date created')),
            ],
        ),
        migrations.AddField(
            model_name='classificationjob',
            name='classified_page',
            field=models.ForeignKey(help_text='The classified page instance', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='classification.PageDownload'),
        ),
        migrations.AddField(
            model_name='classificationjob',
            name='classifier_used',
            field=models.ForeignKey(help_text='Which classifier was used', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='classification.Classifier'),
        ),
    ]
