# Generated by Django 2.0.6 on 2018-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationjob',
            name='date_ended',
            field=models.DateTimeField(default=None, help_text='Date when the job ended', null=True),
        ),
    ]
