# Generated by Django 2.0.6 on 2018-06-16 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20180616_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedownload',
            name='content',
            field=models.TextField(help_text="Html content(if null it means it hasn't been downloaded yet", null=True),
        ),
        migrations.AlterField(
            model_name='pagedownload',
            name='url',
            field=models.TextField(help_text='Url', unique=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
