# Generated by Django 2.0.6 on 2018-07-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0005_auto_20180616_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationjob',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='classificationresult',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='classifier',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='pagedownload',
            options={'ordering': ('-id',)},
        ),
    ]
